/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jvfaelfsmpigdeiypuic"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2ZmFlbGZzbXBpZ2RlaXlwdWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjgwMTYsImV4cCI6MjA3Nzk0NDAxNn0.6HLRuqEKcA4gJh57Ss_c-hkI8zatYhYRc-5Qrmo4l9o"